version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/server
hooks:
  BeforeInstall:
    - location: /scripts/install_dependencies.sh
      timeout: 500
      runas: root
  AfterInstall:
    - location: /scripts/change_permissions.sh
      timeout: 500
      runas: root
  ApplicationStart:
    - location: /scripts/start_server.sh
      timeout: 500
      runas: root
  ApplicationStop:
    - location: /scripts/stop_server.sh
      timeout: 500
      runas: root
